@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDY2OTY2OTF9.KDKlKVSSGiicsa9vwHUd3a6AX7Jk2A2WEAETcf74XvQ

### Users create (signup)
POST {{domain}}/users
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{domain}}/sessions
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "password"
}

### Content-Type: application/json
### Authorization: Bearer {{jwt}}